# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <-  2.25

# e.g. "jessica_wardinatus"    
species.name <- "hansuvius"

# e.g. "turquoise"    
color <- "hotpink"

# tip: pick a color at using rstudio colour picker. Addins > Colour Picker