# !! PLEASE DO NOT EDIT THIS FILE !!
# ** make a copy and edit that instead **
# ________________________________________________
# input parameters

# sigma2: 0 < value < 5
sig2 <-  1.7

# e.g. "jessica_wardinatus"    
species.name <- "cinclus_bolamensis"

# e.g. "turquoise"    
color <- "#51463b"

# tip: pick a color at using rstudio colour picker. Addins > Colour Picker